<?php
/**
 * Конфигурация переименования подкатегорий и групп связанных товаров.
 *
 * 'display' — читаемое название для отображения на сайте
 * 'group'   — группа связанных подкатегорий (товары из одной группы показываются
 *             в блоке «Ассортимент» на страницах подкатегорий)
 */
return [
    'armatura-armatura' => ['display' => 'Арматура', 'group' => 'sortovoy'],
    'armatura-katanka' => ['display' => 'Катанка', 'group' => 'sortovoy'],
    'balki-balki-dvutavrovye' => ['display' => 'Балки двутавровые', 'group' => 'sortovoy'],
    'balki-balki-dvutavrovye-nizkoleg' => ['display' => 'Балки двутавровые низколегированные', 'group' => 'sortovoy'],
    'detali-truboprovodov-detali-truboprovodov-flanets' => ['display' => 'Фланцы (трубопроводные)', 'group' => 'detali'],
    'detali-truboprovodov-detali-truboprovodov-otvod' => ['display' => 'Отводы (трубопроводные)', 'group' => 'detali'],
    'detali-truboprovodov-fitingi-rezbovye' => ['display' => 'Фитинги резьбовые', 'group' => 'detali'],
    'detali-truboprovodov-flantsy-stalnye' => ['display' => 'Фланцы стальные', 'group' => 'detali'],
    'detali-truboprovodov-otvody-stalnye' => ['display' => 'Отводы стальные', 'group' => 'detali'],
    'detali-truboprovodov-perekhody-stalnye' => ['display' => 'Переходы стальные', 'group' => 'detali'],
    'detali-truboprovodov-prokladki' => ['display' => 'Прокладки', 'group' => 'detali'],
    'detali-truboprovodov-sgony-bochata-rezby' => ['display' => 'Сгоны, бочата, резьбы', 'group' => 'detali'],
    'detali-truboprovodov-troyniki-stalnye' => ['display' => 'Тройники стальные', 'group' => 'detali'],
    'detali-truboprovodov-zaglushki-stalnye' => ['display' => 'Заглушки стальные', 'group' => 'detali'],
    'izdeliya-i-proektnye-pozitsii-gazgoldernaya' => ['display' => 'Газгольдерная', 'group' => 'izdeliya'],
    'izdeliya-i-proektnye-pozitsii-list-asbestotsementnyy-ploskiy' => ['display' => 'Лист асбестоцементный', 'group' => 'izdeliya'],
    'izdeliya-i-proektnye-pozitsii-shifer-asbestotsementnyy' => ['display' => 'Шифер асбестоцементный', 'group' => 'izdeliya'],
    'kachestvennye-i-spetsialnye-stali-lenta-iz-pretsiz-splavov' => ['display' => 'Лента из прецизионных сплавов', 'group' => 'kachestvennye'],
    'kachestvennye-i-spetsialnye-stali-lenta-nikhromovaya' => ['display' => 'Лента нихромовая', 'group' => 'kachestvennye'],
    'kachestvennye-i-spetsialnye-stali-pokovka' => ['display' => 'Поковка', 'group' => 'kachestvennye'],
    'kachestvennye-i-spetsialnye-stali-provoloka-armir-dlya-zhbk' => ['display' => 'Проволока для ЖБК', 'group' => 'kachestvennye'],
    'kachestvennye-i-spetsialnye-stali-provoloka-kach-kh-v' => ['display' => 'Проволока холоднотянутая', 'group' => 'kachestvennye'],
    'kachestvennye-i-spetsialnye-stali-provoloka-kach-pruzhinnaya' => ['display' => 'Проволока пружинная', 'group' => 'kachestvennye'],
    'kachestvennye-i-spetsialnye-stali-provoloka-nikhromovaya' => ['display' => 'Проволока нихромовая', 'group' => 'kachestvennye'],
    'kachestvennye-i-spetsialnye-stali-stal-fason-profili-kvadrat' => ['display' => 'Квадрат стальной фасонный', 'group' => 'kachestvennye'],
    'kachestvennye-i-spetsialnye-stali-stal-fason-profili-polosa' => ['display' => 'Полоса стальная фасонная', 'group' => 'kachestvennye'],
    'kachestvennye-i-spetsialnye-stali-stal-konstruktsionnaya-nikel-krug' => ['display' => 'Круг стальной никелевый', 'group' => 'kachestvennye'],
    'kachestvennye-i-spetsialnye-stali-stal-konstruktsionnaya-nikel-kvadrat' => ['display' => 'Квадрат стальной никелевый', 'group' => 'kachestvennye'],
    'kachestvennye-i-spetsialnye-stali-stal-serebryanka' => ['display' => 'Сталь серебрянка', 'group' => 'kachestvennye'],
    'kachestvennye-i-spetsialnye-stali-stal-sort-instrum-krug' => ['display' => 'Круг стальной инструментальный', 'group' => 'kachestvennye'],
    'kachestvennye-i-spetsialnye-stali-stal-sort-kh-t-kalibrovka-krug' => ['display' => 'Круг стальной калиброванный', 'group' => 'kachestvennye'],
    'kachestvennye-i-spetsialnye-stali-stal-sort-kh-t-kalibrovka-shestigrannik' => ['display' => 'Шестигранник стальной калиброванный', 'group' => 'kachestvennye'],
    'kachestvennye-i-spetsialnye-stali-stal-sort-konstr-krug' => ['display' => 'Круг стальной конструкционный', 'group' => 'kachestvennye'],
    'kachestvennye-i-spetsialnye-stali-stal-sort-konstr-shestigrannik' => ['display' => 'Шестигранник стальной конструкционный', 'group' => 'kachestvennye'],
    'kachestvennye-i-spetsialnye-stali-stal-sort-nerzh-zharopr-krug' => ['display' => 'Круг нержавеющий жаропрочный', 'group' => 'kachestvennye'],
    'kachestvennye-i-spetsialnye-stali-stal-sort-nerzh-zharopr-shestigrannik' => ['display' => 'Шестигранник нержавеющий жаропрочный', 'group' => 'kachestvennye'],
    'kachestvennye-i-spetsialnye-stali-stal-sort-spets-sv-mi-krug' => ['display' => 'Круг стальной специальный Св-Ми', 'group' => 'kachestvennye'],
    'krepezh-i-metizy-ankernaya-tekhnika' => ['display' => 'Анкерная техника', 'group' => 'krepezh'],
    'krepezh-i-metizy-bolty' => ['display' => 'Болты', 'group' => 'krepezh'],
    'krepezh-i-metizy-dyubelnaya-tekhnika' => ['display' => 'Дюбельная техника', 'group' => 'krepezh'],
    'krepezh-i-metizy-dyubelya' => ['display' => 'Дюбеля', 'group' => 'krepezh'],
    'krepezh-i-metizy-elektrody-svarochnye' => ['display' => 'Электроды сварочные', 'group' => 'elektrody'],
    'krepezh-i-metizy-gayki' => ['display' => 'Гайки', 'group' => 'krepezh'],
    'krepezh-i-metizy-gvozdi' => ['display' => 'Гвозди', 'group' => 'krepezh'],
    'krepezh-i-metizy-kanaty' => ['display' => 'Канаты', 'group' => 'kanaty'],
    'krepezh-i-metizy-lenta-kh-k-upakovochnaya' => ['display' => 'Лента упаковочная', 'group' => 'lenta'],
    'krepezh-i-metizy-metricheskiy-krepezh' => ['display' => 'Метрический крепёж', 'group' => 'krepezh'],
    'krepezh-i-metizy-obshchiy-krepezh' => ['display' => 'Общий крепёж', 'group' => 'krepezh'],
    'krepezh-i-metizy-perforirovannyy-krepezh' => ['display' => 'Перфорированный крепёж', 'group' => 'krepezh'],
    'krepezh-i-metizy-samorezy' => ['display' => 'Саморезы', 'group' => 'krepezh'],
    'krepezh-i-metizy-shayby' => ['display' => 'Шайбы', 'group' => 'krepezh'],
    'krepezh-i-metizy-shpilka-rezbovaya-din-975' => ['display' => 'Шпилька резьбовая DIN 975', 'group' => 'krepezh'],
    'krepezh-i-metizy-shpilki' => ['display' => 'Шпильки', 'group' => 'krepezh'],
    'krepezh-i-metizy-shplinty' => ['display' => 'Шплинты', 'group' => 'krepezh'],
    'krepezh-i-metizy-shurupy' => ['display' => 'Шурупы', 'group' => 'krepezh'],
    'krepezh-i-metizy-takelazh' => ['display' => 'Такелаж', 'group' => 'kanaty'],
    'krepezh-i-metizy-tsepi' => ['display' => 'Цепи', 'group' => 'kanaty'],
    'krepezh-i-metizy-vinty' => ['display' => 'Винты', 'group' => 'krepezh'],
    'krug-kvadrat-polosa-krug-g-k' => ['display' => 'Круг горячекатаный', 'group' => 'sortovoy'],
    'krug-kvadrat-polosa-kvadrat-g-k' => ['display' => 'Квадрат горячекатаный', 'group' => 'sortovoy'],
    'krug-kvadrat-polosa-polosa-g-k' => ['display' => 'Полоса горячекатаная', 'group' => 'sortovoy'],
    'listovoy-prokat-list-riflenyy' => ['display' => 'Лист рифлёный', 'group' => 'listovoy'],
    'listovoy-prokat-prosechno-vytyazhnoy-list' => ['display' => 'Просечно-вытяжной лист', 'group' => 'listovoy'],
    'listovoy-prokat-stal-list-g-k-konstruktsionnaya' => ['display' => 'Сталь листовая конструкционная', 'group' => 'listovoy'],
    'listovoy-prokat-stal-listovaya-g-k-nizkolegirovannaya' => ['display' => 'Сталь листовая низколегированная', 'group' => 'listovoy'],
    'listovoy-prokat-stal-listovaya-g-k-obych-kachestva' => ['display' => 'Сталь листовая обыкновенного качества', 'group' => 'listovoy'],
    'listovoy-prokat-stal-listovaya-kh-k' => ['display' => 'Сталь листовая горячекатаная', 'group' => 'listovoy'],
    'listovoy-prokat-stal-listovaya-otsinkovannaya-kh-k' => ['display' => 'Сталь листовая оцинкованная', 'group' => 'listovoy'],
    'nerzhaveyushchaya-stal-list-nerzhaveyushchiy' => ['display' => 'Лист нержавеющий', 'group' => 'nerzha-list'],
    'nerzhaveyushchaya-stal-provoloka-nerzhaveyushchaya' => ['display' => 'Проволока нержавеющая', 'group' => 'nerzha-provoloka'],
    'nerzhaveyushchaya-stal-rezka-nerzhaveyushchego' => ['display' => 'Резка нержавеющей стали', 'group' => 'nerzha-rezka'],
    'nerzhaveyushchaya-stal-stal-listovaya-nerzhav-bez-nikelya' => ['display' => 'Лист нержавеющий без никеля', 'group' => 'nerzha-list'],
    'nerzhaveyushchaya-stal-stal-listovaya-nerzhav-nikelesod' => ['display' => 'Лист нержавеющий никелесодержащий', 'group' => 'nerzha-list'],
    'nerzhaveyushchaya-stal-stal-sort-nerzh-nikel-krug' => ['display' => 'Круг нержавеющий', 'group' => 'nerzha-sort'],
    'nerzhaveyushchaya-stal-stal-sort-nerzh-nikel-kvadrat' => ['display' => 'Квадрат нержавеющий', 'group' => 'nerzha-sort'],
    'nerzhaveyushchaya-stal-stal-sort-nerzh-nikel-shestigrannik' => ['display' => 'Шестигранник нержавеющий', 'group' => 'nerzha-sort'],
    'polimery-i-tekhnicheskie-materialy-teploizolyatsiya-kauchuk' => ['display' => 'Теплоизоляция каучук', 'group' => 'polimery'],
    'polimery-i-tekhnicheskie-materialy-teploizolyatsiya-polietilen' => ['display' => 'Теплоизоляция полиэтилен', 'group' => 'polimery'],
    'profnastil-profnastil-okrashennyy' => ['display' => 'Профнастил окрашенный', 'group' => 'profnastil'],
    'profnastil-profnastil-otsinkovannyy' => ['display' => 'Профнастил оцинкованный', 'group' => 'profnastil'],
    'provoloka-provoloka-o-k-torgovaya' => ['display' => 'Проволока отожжённая', 'group' => 'provoloka'],
    'provoloka-provoloka-spl-v-sopr' => ['display' => 'Проволока сварочная', 'group' => 'provoloka'],
    'setka-setka-pletenaya' => ['display' => 'Сетка плетёная', 'group' => 'setka'],
    'setka-setka-stalnaya-svarnaya' => ['display' => 'Сетка стальная сварная', 'group' => 'setka'],
    'setka-setka-stalnaya-tkanaya' => ['display' => 'Сетка стальная тканая', 'group' => 'setka'],
    'shveller-shveller' => ['display' => 'Швеллер', 'group' => 'sortovoy'],
    'shveller-shveller-gnutyy' => ['display' => 'Швеллер гнутый', 'group' => 'sortovoy'],
    'shveller-shveller-nizkolegir' => ['display' => 'Швеллер низколегированный', 'group' => 'sortovoy'],
    'truboprovodnaya-armatura-filtry' => ['display' => 'Фильтры', 'group' => 'armatura'],
    'truboprovodnaya-armatura-gryazeviki' => ['display' => 'Грязевики', 'group' => 'armatura'],
    'truboprovodnaya-armatura-klapany-i-zatvory-obratnye' => ['display' => 'Клапаны и затворы обратные', 'group' => 'armatura'],
    'truboprovodnaya-armatura-kollektory-raspredelitelnye' => ['display' => 'Коллекторы распределительные', 'group' => 'armatura'],
    'truboprovodnaya-armatura-krany-sharovye-latunnye' => ['display' => 'Краны шаровые латунные', 'group' => 'armatura'],
    'truboprovodnaya-armatura-krany-sharovye-stalnye' => ['display' => 'Краны шаровые стальные', 'group' => 'armatura'],
    'truboprovodnaya-armatura-radiatory' => ['display' => 'Радиаторы', 'group' => 'armatura'],
    'truboprovodnaya-armatura-regulyatory-davleniya' => ['display' => 'Регуляторы давления', 'group' => 'armatura'],
    'truboprovodnaya-armatura-uzly-podklyucheniya' => ['display' => 'Узлы подключения', 'group' => 'armatura'],
    'truboprovodnaya-armatura-zadvizhki-chugunnye' => ['display' => 'Задвижки чугунные', 'group' => 'armatura'],
    'truboprovodnaya-armatura-zadvizhki-stalnye' => ['display' => 'Задвижки стальные', 'group' => 'armatura'],
    'truby-alyuminievaya-truba' => ['display' => 'Труба алюминиевая', 'group' => 'alyuminiy'],
    'truby-dyuralevaya-truba' => ['display' => 'Труба дюралевая', 'group' => 'dyural'],
    'truby-latunnaya-truba' => ['display' => 'Труба латунная', 'group' => 'latun'],
    'truby-mednaya-trubka' => ['display' => 'Трубка медная', 'group' => 'med'],
    'truby-truby-asbestotsementnye' => ['display' => 'Трубы асбестоцементные', 'group' => 'truby-asbest'],
    'truby-truby-chugunnye-bezrastrubnye-sml' => ['display' => 'Трубы чугунные SML', 'group' => 'truby'],
    'truby-truby-elektrosvarnye' => ['display' => 'Электросварные трубы', 'group' => 'truby'],
    'truby-truby-elektrosvarnye-kvadrat' => ['display' => 'Трубы профильные квадратные', 'group' => 'truby'],
    'truby-truby-elektrosvarnye-oval' => ['display' => 'Трубы профильные овальные', 'group' => 'truby'],
    'truby-truby-elektrosvarnye-pryamoug' => ['display' => 'Трубы профильные прямоугольные', 'group' => 'truby'],
    'truby-truby-g-d-katanye-nefteprov-gost8732-78' => ['display' => 'Трубы бесшовные горячедеформированные', 'group' => 'truby'],
    'truby-truby-kh-d-tyanutye-besshovnye-gost8734-75' => ['display' => 'Трубы бесшовные холоднодеформированные', 'group' => 'truby'],
    'truby-truby-nerzhav-besshovnye' => ['display' => 'Трубы нержавеющие бесшовные', 'group' => 'truby-nerzha'],
    'truby-truby-nerzhav-el-svarnye' => ['display' => 'Трубы нержавеющие электросварные', 'group' => 'truby-nerzha'],
    'truby-truby-vodogazoprov-chernye-gost-3262-75' => ['display' => 'Трубы ВГП чёрные', 'group' => 'truby'],
    'truby-truby-vodogazoprov-otsink-gost-3262-75' => ['display' => 'Трубы ВГП оцинкованные', 'group' => 'truby'],
    'tsvetnye-metally-alyuminievaya-plita' => ['display' => 'Плита алюминиевая', 'group' => 'alyuminiy'],
    'tsvetnye-metally-alyuminievaya-provoloka' => ['display' => 'Проволока алюминиевая', 'group' => 'alyuminiy'],
    'tsvetnye-metally-alyuminievyy-krug' => ['display' => 'Круг алюминиевый', 'group' => 'alyuminiy'],
    'tsvetnye-metally-alyuminievyy-list' => ['display' => 'Лист алюминиевый', 'group' => 'alyuminiy'],
    'tsvetnye-metally-alyuminievyy-profil' => ['display' => 'Профиль алюминиевый', 'group' => 'alyuminiy'],
    'tsvetnye-metally-alyuminievyy-ugolok' => ['display' => 'Уголок алюминиевый', 'group' => 'alyuminiy'],
    'tsvetnye-metally-bronzovyy-krug' => ['display' => 'Круг бронзовый', 'group' => 'bronza'],
    'tsvetnye-metally-dyuralevaya-plita' => ['display' => 'Плита дюралевая', 'group' => 'dyural'],
    'tsvetnye-metally-dyuralevyy-krug' => ['display' => 'Круг дюралевый', 'group' => 'dyural'],
    'tsvetnye-metally-dyuralevyy-list' => ['display' => 'Лист дюралевый', 'group' => 'dyural'],
    'tsvetnye-metally-dyuralevyy-shestigrannik' => ['display' => 'Шестигранник дюралевый', 'group' => 'dyural'],
    'tsvetnye-metally-latunnaya-lenta' => ['display' => 'Лента латунная', 'group' => 'latun'],
    'tsvetnye-metally-latunnyy-krug' => ['display' => 'Круг латунный', 'group' => 'latun'],
    'tsvetnye-metally-latunnyy-list' => ['display' => 'Лист латунный', 'group' => 'latun'],
    'tsvetnye-metally-latunnyy-shestigrannik' => ['display' => 'Шестигранник латунный', 'group' => 'latun'],
    'tsvetnye-metally-mednaya-lenta' => ['display' => 'Лента медная', 'group' => 'med'],
    'tsvetnye-metally-mednyy-krug' => ['display' => 'Круг медный', 'group' => 'med'],
    'tsvetnye-metally-mednyy-list' => ['display' => 'Лист медный', 'group' => 'med'],
    'ugolok-ugolok' => ['display' => 'Уголок', 'group' => 'sortovoy'],
    'ugolok-ugolok-nizkolegir' => ['display' => 'Уголок низколегированный', 'group' => 'sortovoy'],
    'vodostochnaya-sistema-vodostochnaya-sistema' => ['display' => 'Водосточная система', 'group' => 'vodostok'],
];
